services:
  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongo:
        condition: service_started
    environment:
      - RABBITMQ_URL=amqp://rabbitmq
      - MONGO_URL=mongodb://mongo:27017/orders

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 10s
      retries: 5

  worker:
    build: .
    command: node dist/main/server.js
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongo:
        condition: service_started
    environment:
      - RABBITMQ_URL=amqp://rabbitmq
      - MONGO_URL=mongodb://mongo:27017/orders

volumes:
  mongo_data:
